"""Initial migration

Revision ID: 96931aa6373a
Revises: 
Create Date: 2024-01-10 17:55:17.097308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96931aa6373a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
